COIN_DECIMALS = {"SOL": 1000000000, "USDC": 1000000, "USDT": 1000000}
COIN_DECIMAL_AMOUNT = {"SOL": 2, "USDC": 2, "USDT": 2}
REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_DB = 1
REDIS_PASSWORD = None
BINANCE_BALANCE_CACHE = ["USDT", "SOL", "BNB"]
SOLANA_BALANCE_CACHER = ["SOL", "USDT"]
SOLANA_TOKEN_ACCOUNT = {"USDT": "FbFvGG6P2LM6XWiiGVBx6yc3uNxPDzKdFriRerYd5NfX"}
SOLANA_TOKEN_CACHE = ["USDT"]
SYMBOL_PRICE_ROUND_POINT = {"SOL": 2}
PROFIT_PERCENT = 0.25
SLIPPAGE = 0.1

